FROM amazon/dynamodb-local

# USER root

# WORKDIR /home/dynamodblocal

# # UID=1000 → DynamoDB Local の実行ユーザ
# RUN mkdir /home/dynamodblocal/data
# VOLUME /home/dynamodblocal/data
# RUN chown -R dynamodblocal.dynamodblocal data
# RUN mkdir data && chown -R dynamodblocal.dynamodblocal data
# RUN mkdir data && chmod -R 777 data && chown -R 1000 data
